name: CI
on: [create, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: |
        yarn install
    # - name: Run Build
    #   run: yarn run build
    # - name: Run Tests
    #   run: make test
    # - name: Run Lint
    #   run: make lint
    # - name: Publishing Coverage
    #   run: npx codecov
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
